### ISSUE TITLE
内网某台机子报错，其他机子同样代码没问题。初步估计是环境问题，报错不明显啊

### ISSUE THREAD

**Issue by saiye** [aliyun/aliyun-oss-php-sdk#150]
```
OSS\Core\OssException: :  RequestId: 5F86B4F599DD863533113F06 in file /data/wwwroot/lrs-server/vendor/aliyuncs/oss-sdk-php/src/OSS/Result/Result.php on line 97

#0 /data/wwwroot/lrs-server/vendor/aliyuncs/oss-sdk-php/src/OSS/Result/Result.php(28): OSS\Result\Result->parseResponse()
#1 /data/wwwroot/lrs-server/vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php(1417): OSS\Result\Result->__construct(Object(OSS\Http\ResponseCore))
#2 /data/wwwroot/lrs-server/vendor/iidestiny/flysystem-oss/src/OssAdapter.php(492): OSS\OssClient->doesObjectExist('langrens', 'app/local/qrCod...')
#3 /data/wwwroot/lrs-server/vendor/league/flysystem/src/Filesystem.php(57): Iidestiny\Flysystem\Oss\OssAdapter->has('app/local/qrCod...')
#4 /data/wwwroot/lrs-server/vendor/league/flysystem/src/Filesystem.php(98): League\Flysystem\Filesystem->has('app/local/qrCod...')
#5 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(231): League\Flysystem\Filesystem->put('app/local/qrCod...', '\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...', Object(League\Flysystem\Config))
#6 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(368): Illuminate\Filesystem\FilesystemAdapter->put('app/local/qrCod...', '\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...')
#7 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Filesystem\FilesystemManager->__call('put', Array)
#8 /data/wwwroot/lrs-server/app/Http/Controllers/Wx/QrCodeController.php(144): Illuminate\Support\Facades\Facade::__callStatic('put', Array)
#9 [internal function]: App\Http\Controllers\Wx\QrCodeController->appQrCode()
#10 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#11 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('appQrCode', Array)
#12 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Wx\QrCodeController), 'appQrCode')
#13 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#14 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#15 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /data/wwwroot/lrs-server/app/Http/Middleware/ApiLogRecord.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\ApiLogRecord->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#21 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#22 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /data/wwwroot/lrs-server/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /data/wwwroot/lrs-server/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /data/wwwroot/lrs-server/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /data/wwwroot/lrs-server/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /data/wwwroot/lrs-server/public/index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}
```

**Comment by saiye** [comment]
系统时间问题
